// AUTO-GENERATED by scripts/build-stats.mjs from public/data/eda_facts.json.
// Do NOT edit by hand and do NOT hardcode these numbers in components (regla #0).
export const SITE_STATS = {
  nObs: 27911,
  nMonths: 298,
  nSeriesStructural: 194,
  pctFrozen: 45,
  dateFirst: "2001-12",
  dateLast: "2026-09",
  horizonMonths: 12,
  nModels: 24,
  releaseId: "2026-09-158ec972c234",
  releaseStatus: "stale",
} as const;
