// AUTO-GENERATED by scripts/build-stats.mjs from public/data/eda_facts.json.
// Do NOT edit by hand and do NOT hardcode these numbers in components (regla #0).
export const SITE_STATS = {
  nObs: 27611,
  nMonths: 296,
  nSeriesStructural: 194,
  pctFrozen: 45,
  dateFirst: "2001-12",
  dateLast: "2026-07",
  horizonMonths: 12,
  releaseId: "2026-07-4c92ba93ce7d",
  releaseStatus: "stale",
} as const;
