"use client";

// Exploratory data analysis (EDA) of the panel: an automatic, series-by-series
// census regenerated by the data repo on every new bulletin. Reads the baked
// /data/eda_facts.json (fetched at build by scripts/fetch-data.mjs) — every
// number rendered here comes from that JSON, nothing is hardcoded. The full
// standalone report ships as /data/eda_report.pdf.

import * as React from "react";
import dynamic from "next/dynamic";
import { Skeleton } from "@/components/ui/skeleton";
import { useLang } from "@/components/lang-provider";
import { loadEdaFacts, type EdaFacts } from "@/lib/data/eda";

// Recharts lives in eda-charts; only fetched when this section mounts.
const EdaCharts = dynamic(() => import("./eda-charts"), {
  ssr: false,
  loading: () => <Skeleton className="mt-6 h-96 w-full" />,
});

const T = {
  es: {
    eyebrow: "Análisis exploratorio",
    title: "Qué hay dentro del panel, serie por serie",
    intro:
      "Censo automático del panel completo: cuántas series existen, cuánta fila acumulan hoy, en qué régimen administrativo vive cada celda y cuándo retrocedieron las fechas. Se recalcula con cada boletín nuevo.",
    obs: "observaciones mensuales",
    series: "series estructurales",
    evaluable: "evaluables",
    bulletins: "boletines completos",
    trainable: "celdas con fecha específica (F)",
    download: "Descargar el reporte EDA (PDF, 14 páginas)",
    vintageNote:
      "Reporte generado automáticamente ({vintage}); se regenera con cada boletín nuevo del Visa Bulletin.",
    asOf: "corte",
  },
  en: {
    eyebrow: "Exploratory analysis",
    title: "What is inside the panel, series by series",
    intro:
      "An automatic census of the full panel: how many series exist, how much backlog they accumulate today, which administrative regime each cell lives in, and when dates moved backwards. It is recomputed with every new bulletin.",
    obs: "monthly observations",
    series: "structural series",
    evaluable: "evaluable",
    bulletins: "complete bulletins",
    trainable: "cells with a specific date (F)",
    download: "Download the EDA report (PDF, 14 pages)",
    vintageNote:
      "Report generated automatically ({vintage}); it regenerates with every new Visa Bulletin.",
    asOf: "as of",
  },
};

function Stat({ value, label, sub }: { value: string; label: string; sub?: string }) {
  return (
    <div className="min-w-[8rem] flex-1">
      <div className="font-serif text-3xl font-bold text-[var(--color-ink)]">
        {value}
        {sub ? <span className="ml-2 text-base font-normal text-[var(--color-muted)]">{sub}</span> : null}
      </div>
      <div className="mt-1 text-sm text-[var(--color-muted)]">{label}</div>
    </div>
  );
}

// "2026-07" -> "julio 2026" / "July 2026" (UTC-pinned so the month never shifts).
function vintageLabel(vintage: string, lang: "es" | "en"): string {
  const [y, m] = vintage.split("-").map(Number);
  if (!y || !m) return vintage;
  const month = new Intl.DateTimeFormat(lang === "es" ? "es-MX" : "en-US", {
    month: "long",
    timeZone: "UTC",
  }).format(new Date(Date.UTC(y, m - 1, 1)));
  return `${month} ${y}`;
}

export function Eda() {
  const { lang } = useLang();
  const t = T[lang];
  const locale = lang === "es" ? "es-MX" : "en-US";
  const [facts, setFacts] = React.useState<EdaFacts | null>(null);
  const [loaded, setLoaded] = React.useState(false);

  React.useEffect(() => {
    let alive = true;
    loadEdaFacts().then((f) => {
      if (alive) {
        setFacts(f);
        setLoaded(true);
      }
    });
    return () => {
      alive = false;
    };
  }, []);

  if (!loaded) return <Skeleton className="h-64 w-full" />;
  if (!facts) return null; // census not shipped -> render nothing

  const p = facts.panel;

  return (
    <section id="eda" className="mx-auto w-full max-w-5xl px-4 py-12" aria-labelledby="eda-title">
      <p className="text-xs font-semibold uppercase tracking-wider text-[var(--color-accent)]">{t.eyebrow}</p>
      <h2 id="eda-title" className="mt-1 font-serif text-2xl font-bold text-[var(--color-ink)]">
        {t.title}
      </h2>
      <p className="mt-2 max-w-3xl text-[var(--color-muted)]">{t.intro}</p>

      <div className="mt-6 flex flex-wrap gap-6 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5">
        <Stat value={p.n_obs.toLocaleString(locale)} label={t.obs} />
        <Stat
          value={String(p.n_series_structural)}
          sub={`${p.n_series_evaluable} ${t.evaluable}`}
          label={t.series}
        />
        <Stat value={`${p.n_months}/${p.n_months}`} label={t.bulletins} />
        <Stat value={`${p.pct_trainable_F}%`} label={t.trainable} />
      </div>

      <EdaCharts facts={facts} />

      <div className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-3">
        <a
          href="/data/eda_report.pdf"
          target="_blank"
          rel="noopener"
          className="inline-flex items-center gap-2 rounded-lg border border-[var(--color-accent)] px-4 py-2 text-sm font-semibold text-[var(--color-accent)] transition-colors hover:bg-[var(--color-accent)] hover:text-[var(--color-bg)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-accent)]"
        >
          {t.download}
        </a>
        <p className="text-xs text-[var(--color-muted)]">
          {t.vintageNote.replace("{vintage}", `${t.asOf} ${vintageLabel(facts.vintage, lang)}`)}
        </p>
      </div>
    </section>
  );
}
