"use client";

// Exploratory data analysis (EDA) of the panel: an automatic, series-by-series
// census regenerated by the data repo on every new bulletin. Reads the baked
// /data/eda_facts.json (fetched at build by scripts/fetch-data.mjs) — every
// number rendered here comes from that JSON, nothing is hardcoded. The full
// standalone report ships as /data/eda_report.pdf.

import * as React from "react";
import dynamic from "next/dynamic";
import { Skeleton } from "@/components/ui/skeleton";
import { useLang } from "@/components/lang-provider";
import { EdaGallery } from "@/components/sections/eda-gallery";
import { loadEdaFacts, type EdaFacts } from "@/lib/data/eda";

// Recharts lives in eda-charts; only fetched when this section mounts.
const EdaCharts = dynamic(() => import("./eda-charts"), {
  ssr: false,
  loading: () => <Skeleton className="mt-6 h-96 w-full" />,
});

const T = {
  es: {
    eyebrow: "Análisis exploratorio",
    title: "Qué hay dentro del panel, serie por serie",
    intro:
      "Censo automático del panel completo: cuántas series existen, cuánta fila acumulan hoy, en qué régimen administrativo vive cada celda y cuándo retrocedieron las fechas. Se recalcula con cada boletín nuevo.",
    obs: "observaciones mensuales",
    series: "series estructurales",
    evaluable: "evaluables",
    bulletins: "boletines completos",
    trainable: "celdas con fecha específica (F)",
    download: "Descargar el reporte EDA (PDF)",
    vintageNote:
      "Reporte generado automáticamente ({vintage}); se regenera con cada boletín nuevo del Visa Bulletin.",
    asOf: "corte",
  },
  en: {
    eyebrow: "Exploratory analysis",
    title: "What is inside the panel, series by series",
    intro:
      "An automatic census of the full panel: how many series exist, how much backlog they accumulate today, which administrative regime each cell lives in, and when dates moved backwards. It is recomputed with every new bulletin.",
    obs: "monthly observations",
    series: "structural series",
    evaluable: "evaluable",
    bulletins: "complete bulletins",
    trainable: "cells with a specific date (F)",
    download: "Download the EDA report (PDF)",
    vintageNote:
      "Report generated automatically ({vintage}); it regenerates with every new Visa Bulletin.",
    asOf: "as of",
  },
};

function Stat({ value, label, sub }: { value: string; label: string; sub?: string }) {
  return (
    <div className="min-w-[8rem] flex-1">
      <div className="font-serif text-3xl font-bold text-[var(--color-ink)]">
        {value}
        {sub ? <span className="ml-2 text-base font-normal text-[var(--color-muted)]">{sub}</span> : null}
      </div>
      <div className="mt-1 text-sm text-[var(--color-muted)]">{label}</div>
    </div>
  );
}

// "2026-07" -> "julio 2026" / "July 2026" (UTC-pinned so the month never shifts).
function vintageLabel(vintage: string, lang: "es" | "en"): string {
  const [y, m] = vintage.split("-").map(Number);
  if (!y || !m) return vintage;
  const month = new Intl.DateTimeFormat(lang === "es" ? "es-MX" : "en-US", {
    month: "long",
    timeZone: "UTC",
  }).format(new Date(Date.UTC(y, m - 1, 1)));
  return `${month} ${y}`;
}

export function Eda() {
  const { lang } = useLang();
  const t = T[lang];
  const locale = lang === "es" ? "es-MX" : "en-US";
  const [facts, setFacts] = React.useState<EdaFacts | null>(null);
  const [loaded, setLoaded] = React.useState(false);

  React.useEffect(() => {
    let alive = true;
    loadEdaFacts().then((f) => {
      if (alive) {
        setFacts(f);
        setLoaded(true);
      }
    });
    return () => {
      alive = false;
    };
  }, []);

  // audit M3: the #eda anchor must exist even while loading / on failure —
  // the prose deep-link, the RAG link and the nav TOC all target it.
  if (!loaded)
    return (
      <section id="eda" className="section">
        <div className="section-inner">
          <Skeleton className="h-64 w-full" />
        </div>
      </section>
    );
  if (!facts) return <section id="eda" aria-hidden="true" />; // census not shipped

  const p = facts.panel;
  // audit L3: the completeness tile's denominator is the EXPECTED span from the
  // census dates — n_months/n_months could never show a hole.
  const [y0, m0] = p.date_first.split("-").map(Number);
  const [y1, m1] = p.date_last.split("-").map(Number);
  const expectedMonths = y0 && y1 ? (y1 - y0) * 12 + (m1 - m0) + 1 : p.n_months;

  return (
    // AX1: same editorial scaffold as every other section (.section >
    // .section-inner with section-tag/-title/-sub), on the shared rail.
    <section id="eda" className="section" aria-labelledby="eda-title">
      <div className="section-inner">
      <span className="section-tag">{t.eyebrow}</span>
      <h2 id="eda-title" className="section-title">
        {t.title}
      </h2>
      <p className="section-sub">{t.intro}</p>

      {/* stats as a typographic group under a module rule — no boxed card */}
      <div className="flex flex-wrap gap-x-10 gap-y-6 border-t-2 border-[var(--color-rule)] pt-5">
        <Stat value={p.n_obs.toLocaleString(locale)} label={t.obs} />
        <Stat
          value={String(p.n_series_structural)}
          sub={`${p.n_series_evaluable} ${t.evaluable}`}
          label={t.series}
        />
        <Stat value={`${p.n_months}/${expectedMonths}`} label={t.bulletins} />
        <Stat value={`${p.pct_trainable_F}%`} label={t.trainable} />
      </div>

      <EdaCharts facts={facts} />

      <EdaGallery facts={facts} />

      <div className="mt-12 flex flex-wrap items-center gap-x-5 gap-y-3">
        <a
          href={lang === "en" ? "/data/eda_report_en.pdf" : "/data/eda_report.pdf"}
          target="_blank"
          rel="noopener"
          className="inline-flex items-center gap-2 rounded-lg border border-[var(--color-accent)] px-4 py-2 text-sm font-semibold text-[var(--color-accent)] transition-colors hover:bg-[var(--color-accent)] hover:text-[var(--color-bg)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-accent)]"
        >
          {t.download}
        </a>
        <p className="text-xs text-[var(--color-muted)]">
          {t.vintageNote.replace("{vintage}", `${t.asOf} ${vintageLabel(facts.vintage, lang)}`)}
        </p>
      </div>
      </div>
    </section>
  );
}
