"use client";

// Annotated gallery of the 7 feature-engineering figures, regenerated by the
// data repo together with fe_facts.json. Same four-variant contract as the EDA
// gallery (language × theme under public/data/fe/{,dark/,en/,en/dark/}): the
// language is route-driven, both theme <img>s are in the DOM and CSS-toggled
// via the `dark:` variant, and each variant renders with its own MEASURED
// intrinsic size from /data/fig_dims.json (component constants are only the
// fallback for files missing from that map).
//
// Caption copy mirrors the rationale strings in fe_facts.json — the same
// terminology as the FE report (regla #0) — and every drifting number is
// DERIVED at render time from the fetched facts (ledger counts, the gap cap,
// the lag count, the selection funnel). Only stable structural facts stay
// literal (the Dec-2001 panel start, the figures' example series, the four
// parser regimes, the six pipeline stages).

import * as React from "react";
import { localeOf } from "@/lib/i18n";
import { useLang } from "@/components/lang-provider";
import { FigureLink } from "@/components/sections/eda-gallery";
import type { FeFacts } from "@/lib/data/fe";
import { figDim, type Dim } from "@/lib/data/fig-dims";

type LangDims = { light: Dim; dark: Dim };
type Fig = { id: string; es: LangDims; en: LangDims };

// Display order is the narrative order (raw cell → pipeline → target → model
// features), not the file numbering. Fallback dimensions measured per language
// from the shipped PNGs (the header textwrap re-flows with translated copy).
const dims = (w: number, h: number): LangDims => ({ light: { w, h }, dark: { w, h } });
const FIGS: Fig[] = [
  { id: "f06_parser", es: dims(2470, 1538), en: dims(2470, 1536) },
  { id: "f07_pipeline", es: dims(3176, 1251), en: dims(3176, 1186) },
  { id: "f05_regime", es: dims(2529, 1952), en: dims(2529, 1949) },
  { id: "f04_gaps", es: dims(2529, 1822), en: dims(2529, 1818) },
  { id: "f01_differencing", es: dims(2353, 1882), en: dims(2353, 1828) },
  { id: "f02_calendar", es: dims(2353, 1464), en: dims(2353, 1464) },
  { id: "f03_importance", es: dims(2390, 1471), en: dims(2345, 1471) },
];

// ── Derived values (every caption number refreshes with the regenerated JSON) ──
type Derived = {
  yrs: number; // years of format drift (vintage year − 2001)
  gapCap: number; // max interpolable gap, months
  lags: number; // 24
  nRows: string; // "27,611" (locale)
  nSeries: number; // 194
  dups: number; // duplicates collapsed
  unparseable: number; // unparseable F priority dates
  jumps: number; // >8-year jumps annotated
  pctF: number; // 58
  selIn: number; // 44
  selOut: number; // 1
};

function derive(facts: FeFacts, lang: "es" | "en"): Derived {
  const locale = localeOf(lang);
  const led = facts.cleaning_ledger;
  const vintageYear = Number(facts.vintage.split("-")[0]);
  return {
    yrs: Number.isFinite(vintageYear) ? vintageYear - 2001 : 0,
    gapCap: facts.constants.max_interpolable_gap,
    lags: facts.constants.lags,
    nRows: led.n_rows.toLocaleString(locale),
    nSeries: led.n_series,
    dups: led.dup_collapsed,
    unparseable: led.f_priority_date_unparseable,
    jumps: led.big_jumps_gt_8y,
    pctF: led.n_rows > 0 ? Math.round((led.rows_by_status.F / led.n_rows) * 100) : 0,
    selIn: facts.feature_selection.n_features_in,
    selOut: facts.feature_selection.n_selected,
  };
}

type FigCopy = {
  tag: string;
  headline: (d: Derived) => string;
  body: (d: Derived) => string;
  alt: string; // static and number-free by design (no unguarded drift)
};

const T: Record<
  "es" | "en",
  {
    title: string;
    sub: string;
    figura: string;
    fullSize: string;
    openOriginal: string;
    close: string;
    figs: Record<string, FigCopy>;
  }
> = {
  es: {
    title: "Galería comentada",
    sub: "Siete figuras del reporte de ingeniería de características, cada una con su decisión. Se regeneran con cada boletín.",
    figura: "Figura",
    fullSize: "Ver a tamaño completo",
    openOriginal: "Abrir original",
    close: "Cerrar",
    figs: {
      f06_parser: {
        tag: "El parser",
        headline: (d) => `${d.yrs} años de deriva de formato, normalizados a cuatro regímenes`,
        body: () =>
          "Cada fila llama al parser real (vp_data.visa_common) con la celda tal como se publicó: fechas '01MAY16' con pivote de siglo y guardia de época, footnotes tolerados (C*/U*), erratas ('4rd') y celdas vacías que quedan como centinela UNK — nunca el string NA, que pandas leería como NaN. Nada se corrige en silencio: la celda cruda se conserva siempre en raw_value.",
        alt: "Tabla de celdas crudas del boletín frente a su valor parseado y la regla aplicada por el parser tolerante.",
      },
      f07_pipeline: {
        tag: "El pipeline",
        headline: () => "De HTML congelado a objetivo evaluable, cero correcciones en silencio",
        body: (d) =>
          `Seis etapas publican su ledger en cada corrida: ${d.nRows} filas en ${d.nSeries} series, ${d.unparseable} fechas F imparseables y ${d.dups} duplicados colapsados (ceros inalcanzables por construcción: las guardias abortan el build), ${d.jumps} saltos de más de 8 años anotados —jamás recortados— y el ${d.pctF} % del panel con fecha específica (F). El almacén estrella re-verifica el contrato con CHECKs declarativos.`,
        alt: "Diagrama de las seis etapas del pipeline de limpieza, del HTML congelado en S3 a la máscara F-only de evaluación, con el ledger de cada etapa.",
      },
      f05_regime: {
        tag: "Máscara F-only",
        headline: () => "C y U son anotación, no objetivo: solo se puntúan las fechas publicadas",
        body: () =>
          "India · EB-2 (FAD): la línea existe solo en los meses con fecha específica (F); los fondos marcan el régimen administrativo del boletín (Current, Unavailable, sin dato) y la franja inferior muestra los únicos meses que la evaluación puntúa. Aplanar C a fecha y U a NaN destruía el régimen: la columna de estado lo preserva como anotación descriptiva y la máscara F-only lo excluye del objetivo.",
        alt: "Serie de India EB-2 con la línea solo en los meses F, fondos por régimen administrativo y la franja de meses puntuados por la evaluación.",
      },
      f04_gaps: {
        tag: "Política de huecos",
        headline: (d) => `Huecos de hasta ${d.gapCap} meses se interpolan; los largos jamás se inventan`,
        body: (d) =>
          `México · EB-4 (trabajadores religiosos, FAD): los huecos son meses C/U y la ausencia es señal (MNAR). Las corridas cortas (≤${d.gapCap} meses) se interpolan linealmente para la rejilla de entrenamiento — todo o nada por corrida, sin rampas parciales—; las largas quedan vacías y solo el EDA las caracteriza con suavizado de Kalman, porque una rampa inventada fabrica tendencia. El relleno de continuidad jamás se puntúa.`,
        alt: "Serie con huecos: observaciones F reales, interpolaciones cortas, imputación Kalman solo para EDA y el hueco largo que queda vacío.",
      },
      f01_differencing: {
        tag: "Diferenciación",
        headline: () => "Los árboles no extrapolan: se entrena el avance mensual, no el nivel",
        body: () =>
          "Un árbol no extrapola fuera del rango visto: sobre el nivel (décadas de tendencia creciente) se satura en el máximo histórico. Los árboles (XGBoost, LightGBM, CatBoost) predicen la primera diferencia —estacionaria y extrapolable— y el pronóstico se reintegra de forma causal, con una suma acumulada anclada al último nivel observado.",
        alt: "Comparación de la serie en niveles, con tendencia fuerte, contra su primera diferencia estacionaria.",
      },
      f02_calendar: {
        tag: "Calendario cíclico",
        headline: () => "Diciembre y enero son vecinos: el calendario fiscal se codifica en círculo",
        body: () =>
          "El año fiscal de visas arranca en octubre, cuando se reinician las cuotas. Codificar el mes y su posición fiscal con seno/coseno evita imponer un orden falso: un entero 1..12 haría que el modelo viera diciembre y enero —meses vecinos— como los más lejanos. Las componentes salen del encoder canónico que consumen los modelos.",
        alt: "Componentes seno y coseno de la posición del mes en el año fiscal y los doce meses colocados sobre el círculo unitario.",
      },
      f03_importance: {
        tag: "Importancia",
        headline: () => "La memoria manda: el avance reciente domina la importancia",
        body: (d) =>
          `Importancia por ganancia de un LightGBM entrenado sobre el avance mensual de las series familiares FAD, con ${d.lags} rezagos del avance y el calendario cíclico como candidatos: los rezagos recientes concentran la ganancia y el calendario aporta poco — coherente con un panel sin estacionalidad explotable. En el catálogo de caracterización, la selección FRESH + mRMR depura ${d.selIn} características a ${d.selOut}.`,
        alt: "Barras de importancia por ganancia de un LightGBM: los rezagos recientes del avance dominan sobre el calendario cíclico.",
      },
    },
  },
  en: {
    title: "Annotated gallery",
    sub: "Seven figures from the feature-engineering report, each with its decision. They regenerate with every bulletin.",
    figura: "Figure",
    fullSize: "View full size",
    openOriginal: "Open original",
    close: "Close",
    figs: {
      f06_parser: {
        tag: "The parser",
        headline: (d) => `${d.yrs} years of format drift, normalized to four regimes`,
        body: () =>
          "Each row calls the real parser (vp_data.visa_common) with the cell exactly as published: '01MAY16' dates with a century pivot and an epoch guard, tolerated footnotes (C*/U*), typos ('4rd') and empty cells that become the UNK sentinel — never the string NA, which pandas would read as NaN. Nothing is silently corrected: the raw cell is always kept in raw_value.",
        alt: "Table of raw bulletin cells against their parsed value and the rule applied by the tolerant parser.",
      },
      f07_pipeline: {
        tag: "The pipeline",
        headline: () => "From frozen HTML to an evaluable target, zero silent corrections",
        body: (d) =>
          `Six stages publish their ledger on every run: ${d.nRows} rows across ${d.nSeries} series, ${d.unparseable} unparseable F dates and ${d.dups} duplicates collapsed (zeros unreachable by construction: the guards abort the build), ${d.jumps} jumps of more than 8 years annotated — never trimmed — and ${d.pctF}% of the panel with a specific date (F). The star-schema warehouse re-verifies the contract with declarative CHECKs.`,
        alt: "Diagram of the six cleaning-pipeline stages, from frozen HTML on S3 to the F-only evaluation mask, with each stage's ledger.",
      },
      f05_regime: {
        tag: "F-only mask",
        headline: () => "C and U are annotation, not targets: only published dates are scored",
        body: () =>
          "India · EB-2 (FAD): the line exists only in months with a specific date (F); the backgrounds mark the bulletin's administrative regime (Current, Unavailable, no data) and the bottom strip shows the only months the evaluation scores. Flattening C to a date and U to NaN destroyed the regime: the status column preserves it as a descriptive annotation and the F-only mask keeps it out of the target.",
        alt: "India EB-2 series with the line only in F months, backgrounds by administrative regime and the strip of months the evaluation scores.",
      },
      f04_gaps: {
        tag: "Gap policy",
        headline: (d) => `Gaps of up to ${d.gapCap} months are interpolated; long ones are never invented`,
        body: (d) =>
          `Mexico · EB-4 (religious workers, FAD): gaps are C/U months and the absence is signal (MNAR). Short runs (≤${d.gapCap} months) are linearly interpolated for the training grid — all-or-nothing per run, no partial ramps —; long ones stay empty and only the EDA characterizes them with Kalman smoothing, because an invented ramp fabricates trend. The continuity fill is never scored.`,
        alt: "Gappy series: real F observations, short interpolations, Kalman imputation for EDA only, and the long gap left empty.",
      },
      f01_differencing: {
        tag: "Differencing",
        headline: () => "Trees don't extrapolate: they are trained on the monthly advance, not the level",
        body: () =>
          "A tree cannot extrapolate outside the range it saw: on the level (decades of rising trend) it saturates at the historical maximum. The trees (XGBoost, LightGBM, CatBoost) predict the first difference — stationary and extrapolable — and the forecast is reintegrated causally, with a cumulative sum anchored at the last observed level.",
        alt: "Comparison of the series in levels, with a strong trend, against its stationary first difference.",
      },
      f02_calendar: {
        tag: "Cyclic calendar",
        headline: () => "December and January are neighbors: the fiscal calendar is encoded on a circle",
        body: () =>
          "The visa fiscal year starts in October, when quotas reset. Encoding the month and its fiscal position with sine/cosine avoids imposing a false order: an integer 1..12 would make the model see December and January — neighboring months — as the farthest apart. The components come from the canonical encoder the models consume.",
        alt: "Sine and cosine components of the month's position in the fiscal year and the twelve months placed on the unit circle.",
      },
      f03_importance: {
        tag: "Importance",
        headline: () => "Memory rules: the recent advance dominates the importance",
        body: (d) =>
          `Gain importance of a LightGBM trained on the monthly advance of the family FAD series, with ${d.lags} advance lags and the cyclic calendar as candidates: the recent lags concentrate the gain and the calendar contributes little — consistent with a panel without exploitable seasonality. On the characterization catalog, the FRESH + mRMR selection prunes ${d.selIn} features down to ${d.selOut}.`,
        alt: "Gain-importance bars of a LightGBM: the recent advance lags dominate over the cyclic calendar.",
      },
    },
  },
};

export function FeGallery({ facts }: { facts: FeFacts }) {
  const { lang } = useLang();
  const t = T[lang];
  const d = React.useMemo(() => derive(facts, lang), [facts, lang]);

  return (
    <div className="mt-16">
      <h3 className="font-serif text-xl font-bold text-[var(--color-ink)]">{t.title}</h3>
      <p className="mt-1 max-w-3xl text-sm text-[var(--color-muted)]">{t.sub}</p>

      <div className="mt-10 space-y-16">
        {FIGS.map((f, i) => {
          const c = t.figs[f.id];
          const headline = c.headline(d);
          const ariaLabel = `${headline} — ${t.fullSize}`;
          const prefix = lang === "en" ? "fe/en" : "fe";
          const fallback = f[lang];
          return (
            // Ultrawide: mismo patrón AY3 que eda-gallery (decisión AY2 vs AY3
            // documentada allí): dos columnas con caption sticky + breakout
            // moderado hasta min(1600px, 90vw) centrado con márgenes negativos
            // simétricos; el wrapper min-w-0 agrupa ambas variantes de tema en
            // una celda y su 2xl:-mt-5 cancela el mt-5 interno de FigureLink.
            <figure
              key={f.id}
              className="2xl:mx-[calc((100%-min(1600px,90vw))/2)] 2xl:grid 2xl:w-[min(1600px,90vw)] 2xl:grid-cols-[minmax(32ch,38ch)_1fr] 2xl:items-start 2xl:gap-12"
            >
              <figcaption className="2xl:sticky 2xl:top-32">
                <p className="text-xs font-semibold uppercase tracking-wider text-[var(--color-accent)]">
                  {t.figura} {i + 1} · {c.tag}
                </p>
                <h4 className="mt-1.5 font-serif text-2xl font-bold leading-snug text-[var(--color-ink)]">
                  {headline}
                </h4>
                <p className="mt-2 max-w-3xl leading-relaxed text-[var(--color-muted)]">{c.body(d)}</p>
              </figcaption>
              <div className="min-w-0 2xl:-mt-5">
                <FigureLink
                  src={`/data/${prefix}/${f.id}.png`}
                  dim={figDim(`${prefix}/${f.id}.png`, fallback.light)}
                  alt={c.alt}
                  ariaLabel={ariaLabel}
                  hint={t.fullSize}
                  originalLabel={t.openOriginal}
                  closeLabel={t.close}
                  toggle="block dark:hidden"
                  plate="bg-[var(--color-figure-plate)]"
                />
                <FigureLink
                  src={`/data/${prefix}/dark/${f.id}.png`}
                  dim={figDim(`${prefix}/dark/${f.id}.png`, fallback.dark)}
                  alt={c.alt}
                  ariaLabel={ariaLabel}
                  hint={t.fullSize}
                  originalLabel={t.openOriginal}
                  closeLabel={t.close}
                  toggle="hidden dark:block"
                  plate="bg-[var(--color-figure-plate-dark)]"
                  imgAriaHidden
                />
              </div>
            </figure>
          );
        })}
      </div>
    </div>
  );
}
