// Panel-wide EDA census, pre-generated by the data repo (reports/eda/eda_facts.json,
// regenerated by its weekly Action on every new bulletin) and baked at build time
// into /data/eda_facts.json by scripts/fetch-data.mjs. Every number the EDA section
// renders comes from here — nothing is hardcoded in the component.

export type EdaPanel = {
  n_obs: number;
  n_series_structural: number;
  n_series_with_F: number;
  n_series_evaluable: number;
  n_obs_F: number;
  pct_trainable_F: number;
  n_months: number;
  date_first: string; // "YYYY-MM"
  date_last: string; // "YYYY-MM"
  pct_retro: number;
  pct_frozen: number;
  median_step_days: number;
};

export type EdaRegime = { F: number; C: number; U: number; UNK: number };

export type EdaBacklogEntry = {
  country: string;
  block: string; // "family" | "employment"
  category: string;
  table: string; // "FAD" | "DFF"
  backlog_years: number;
};

export type EdaRetroEvent = {
  date: string; // "YYYY-MM"
  country: string;
  block: string;
  category: string;
  table: string;
  days: number;
};

export type EdaFacts = {
  vintage: string; // "YYYY-MM"
  panel: EdaPanel;
  regime: EdaRegime;
  stationarity_summary?: Record<string, number>;
  retro_events: EdaRetroEvent[];
  backlog_today: EdaBacklogEntry[];
};

let cache: Promise<EdaFacts | null> | null = null;

export function loadEdaFacts(): Promise<EdaFacts | null> {
  if (cache) return cache;
  cache = fetch("/data/eda_facts.json")
    .then((r) => (r.ok ? (r.json() as Promise<EdaFacts>) : null))
    .catch(() => null);
  return cache;
}
