// Panel-wide EDA census, pre-generated by the data repo (reports/eda/eda_facts.json,
// regenerated by its weekly Action on every new bulletin) and baked at build time
// into /data/eda_facts.json by scripts/fetch-data.mjs. Every number the EDA section
// renders comes from here — nothing is hardcoded in the component.

export type EdaPanel = {
  n_obs: number;
  n_series_structural: number;
  n_series_with_F: number;
  n_series_evaluable: number;
  n_obs_F: number;
  pct_trainable_F: number;
  n_months: number;
  date_first: string; // "YYYY-MM"
  date_last: string; // "YYYY-MM"
  pct_retro: number;
  pct_frozen: number;
  median_step_days: number;
};

export type EdaRegime = { F: number; C: number; U: number; UNK: number };

export type EdaBacklogEntry = {
  country: string;
  block: string; // "family" | "employment"
  category: string;
  table: string; // "FAD" | "DFF"
  backlog_years: number;
};

export type EdaRetroEvent = {
  date: string; // "YYYY-MM"
  country: string;
  block: string;
  category: string;
  table: string;
  days: number;
};

// Per-series census record (only the fields the UI derives from).
export type EdaSeriesRecord = {
  country: string;
  block: string;
  category: string;
  table: string;
  n_F: number;
  pct_frozen: number;
};

export type EdaGapEntry = {
  country: string;
  block: string;
  category: string;
  date: string; // "YYYY-MM"
  gap_days: number;
};

export type EdaDv = {
  n_rows: number;
  n_regions?: number;
  date_first?: string;
  date_last?: string;
};

export type EdaFacts = {
  vintage: string; // "YYYY-MM"
  panel: EdaPanel;
  regime: EdaRegime;
  stationarity_summary?: Record<string, number>;
  series: EdaSeriesRecord[];
  retro_events: EdaRetroEvent[];
  fad_dff_gap: EdaGapEntry[];
  backlog_today: EdaBacklogEntry[];
  monthly_advance_median: Record<string, number>;
  dv: EdaDv;
};

// Structural check (audit 3-jul M4): a truncated/old JSON must degrade to the
// section hiding itself (null), never to a render crash that blanks the page.
function isEdaFacts(x: unknown): x is EdaFacts {
  if (!x || typeof x !== "object") return false;
  const f = x as Record<string, unknown>;
  const p = f.panel as Record<string, unknown> | undefined;
  return (
    typeof f.vintage === "string" &&
    !!p &&
    typeof p.n_obs === "number" &&
    typeof p.pct_retro === "number" &&
    !!f.regime &&
    typeof (f.regime as Record<string, unknown>).F === "number" &&
    Array.isArray(f.series) &&
    f.series.length > 0 &&
    Array.isArray(f.retro_events) &&
    Array.isArray(f.fad_dff_gap) &&
    Array.isArray(f.backlog_today) &&
    !!f.monthly_advance_median &&
    typeof (f.dv as Record<string, unknown> | undefined)?.n_rows === "number"
  );
}

let cache: Promise<EdaFacts | null> | null = null;

export function loadEdaFacts(): Promise<EdaFacts | null> {
  if (cache) return cache;
  const p = fetch("/data/eda_facts.json")
    .then(async (r) => {
      if (!r.ok) return null;
      const j: unknown = await r.json();
      return isEdaFacts(j) ? j : null;
    })
    .catch(() => null)
    .then((f) => {
      // audit L5: a failed load must not be cached forever — allow retry
      if (!f) cache = null;
      return f;
    });
  cache = p;
  return p;
}
