// Feature-engineering (FE) census, pre-generated by the data repo
// (reports/fe/fe_facts.json, built by experiments/build_fe_facts.py from the
// REAL pipeline modules — constants imported from vp_model/config, ledger from
// the panel build, selection from vp_model/feature_select) and baked at build
// time into /data/fe_facts.json by scripts/fetch-data.mjs. Every number the FE
// section renders comes from here — nothing is hardcoded in the component.

export type FeConstants = {
  base_epoch: string; // "1975-01-01"
  days_per_year: number;
  seasonal_period: number;
  max_interpolable_gap: number; // months
  lags: number;
  min_train: { FAD: number; DFF: number };
  holdout: number;
};

// One master decision (cleaning or FE): title + module path + rationale, all
// authored in the data repo (Spanish source of truth, mirrored by the report).
export type FeDecision = {
  id: string;
  title: string;
  module: string;
  rationale: string;
};

export type FeCleaningLedger = {
  vintage: string; // "YYYY-MM"
  n_rows: number;
  n_series: number;
  rows_by_status: { F: number; C: number; U: number; UNK: number };
  dup_collapsed: number;
  bulletin_date_unparseable: number;
  f_priority_date_unparseable: number;
  epoch_underflow: number;
  big_jumps_gt_8y: number;
};

export type FeFeatureSelection = {
  target: string;
  n_series: number;
  n_features_in: number;
  alpha_fdr: number;
  n_relevant: number;
  n_selected: number;
  relevant: string[];
  selected: string[];
  dropped_redundant: Record<string, string>; // dropped feature -> representative
};

export type FeFacts = {
  vintage: string; // "YYYY-MM"
  fe_version: string;
  constants: FeConstants;
  covariates: Record<string, string[]>; // model -> covariate columns
  differenced_models: string[];
  scaled_models: string[];
  fe_decisions: FeDecision[];
  cleaning_decisions: FeDecision[];
  cleaning_ledger: FeCleaningLedger;
  feature_selection: FeFeatureSelection;
};

const isDecisionArray = (x: unknown): x is FeDecision[] =>
  Array.isArray(x) &&
  x.length > 0 &&
  x.every(
    (d) =>
      !!d &&
      typeof (d as FeDecision).id === "string" &&
      typeof (d as FeDecision).title === "string" &&
      typeof (d as FeDecision).module === "string" &&
      typeof (d as FeDecision).rationale === "string" &&
      (d as FeDecision).title.length > 0 &&
      (d as FeDecision).rationale.length > 0,
  );

// Structural check over EVERY field the UI reads, nested sub-objects included
// (audit: an unvalidated sub-object lets a UI assert a confident lie — a
// truncated/old JSON must degrade to the section hiding itself, never to a
// render crash or a fabricated zero).
function isFeFacts(x: unknown): x is FeFacts {
  if (!x || typeof x !== "object") return false;
  const f = x as Record<string, unknown>;
  const c = f.constants as Record<string, unknown> | undefined;
  const mt = c?.min_train as Record<string, unknown> | undefined;
  const led = f.cleaning_ledger as Record<string, unknown> | undefined;
  const rbs = led?.rows_by_status as Record<string, unknown> | undefined;
  const fs = f.feature_selection as Record<string, unknown> | undefined;
  return (
    typeof f.vintage === "string" &&
    typeof f.fe_version === "string" &&
    !!c &&
    typeof c.base_epoch === "string" &&
    typeof c.max_interpolable_gap === "number" &&
    typeof c.lags === "number" &&
    typeof c.holdout === "number" &&
    !!mt &&
    typeof mt.FAD === "number" &&
    typeof mt.DFF === "number" &&
    !!f.covariates &&
    typeof f.covariates === "object" &&
    Array.isArray(f.differenced_models) &&
    f.differenced_models.length > 0 &&
    Array.isArray(f.scaled_models) &&
    f.scaled_models.length > 0 &&
    isDecisionArray(f.fe_decisions) &&
    isDecisionArray(f.cleaning_decisions) &&
    !!led &&
    typeof led.n_rows === "number" &&
    led.n_rows > 0 &&
    typeof led.n_series === "number" &&
    typeof led.dup_collapsed === "number" &&
    typeof led.bulletin_date_unparseable === "number" &&
    typeof led.f_priority_date_unparseable === "number" &&
    typeof led.epoch_underflow === "number" &&
    typeof led.big_jumps_gt_8y === "number" &&
    !!rbs &&
    typeof rbs.F === "number" &&
    typeof rbs.C === "number" &&
    typeof rbs.U === "number" &&
    typeof rbs.UNK === "number" &&
    !!fs &&
    typeof fs.target === "string" &&
    typeof fs.n_series === "number" &&
    typeof fs.n_features_in === "number" &&
    fs.n_features_in > 0 &&
    typeof fs.alpha_fdr === "number" &&
    typeof fs.n_relevant === "number" &&
    typeof fs.n_selected === "number" &&
    Array.isArray(fs.relevant) &&
    Array.isArray(fs.selected) &&
    fs.selected.length === fs.n_selected &&
    (fs.selected as unknown[]).every((s) => typeof s === "string") &&
    !!fs.dropped_redundant &&
    typeof fs.dropped_redundant === "object"
  );
}

let cache: Promise<FeFacts | null> | null = null;

export function loadFeFacts(): Promise<FeFacts | null> {
  if (cache) return cache;
  const p = fetch("/data/fe_facts.json")
    .then(async (r) => {
      if (!r.ok) return null;
      const j: unknown = await r.json();
      return isFeFacts(j) ? j : null;
    })
    .catch(() => null)
    .then((f) => {
      // a failed load must not be cached forever — allow retry (same as eda.ts)
      if (!f) cache = null;
      return f;
    });
  cache = p;
  return p;
}
