// Real model forecasts (pre-generated by the production pipeline in the
// UACJ-MIAAD/VisaPredictAI repo: experiments/generate_web_forecasts.py).
// Point = winning models per the deliverable (FAD: median Theta+ETS+SARIMA;
// DFF: SARIMA); bands = split-conformal 95/80% widened by √h. The browser
// drift baseline (analytics.buildForecast) is only a fallback for series with
// no pre-generated forecast. Source of truth: /data/forecasts.csv (+ _meta).

export type ForecastPoint = { date: string; days: number; lo80: number; hi80: number; lo95: number; hi95: number };
export type SeriesMeta = { models: string[]; mase: number; last_month: string };
export type ForecastStore = {
  method: Record<string, string>; // table -> human method description
  series: Map<string, ForecastPoint[]>; // "country|category|table" -> 12 future points
  meta: Map<string, SeriesMeta>;
};

const key = (country: string, category: string, table: string) => `${country}|${category}|${table}`;

let cache: Promise<ForecastStore> | null = null;

export function loadForecasts(): Promise<ForecastStore> {
  if (cache) return cache;
  cache = (async () => {
    const empty: ForecastStore = { method: {}, series: new Map(), meta: new Map() };
    let csv: string, metaJson: { method?: Record<string, string>; series?: Record<string, SeriesMeta> };
    try {
      const [c, m] = await Promise.all([
        fetch("/data/forecasts.csv").then((r) => (r.ok ? r.text() : Promise.reject(new Error(`csv ${r.status}`)))),
        fetch("/data/forecasts_meta.json").then((r) => (r.ok ? r.json() : {})),
      ]);
      csv = c;
      metaJson = m;
    } catch {
      return empty; // no forecasts shipped → callers fall back to the drift baseline
    }
    const store: ForecastStore = { method: metaJson.method ?? {}, series: new Map(), meta: new Map() };
    const lines = csv.split("\n");
    const h = lines[0].split(",");
    const ix = (k: string) => h.indexOf(k);
    const I = { c: ix("country"), cat: ix("category"), t: ix("table"), d: ix("date"), days: ix("days"), lo80: ix("lo80"), hi80: ix("hi80"), lo95: ix("lo95"), hi95: ix("hi95") };
    for (let i = 1; i < lines.length; i++) {
      const a = lines[i].split(",");
      if (a.length < 9 || !a[I.c]) continue;
      const k = key(a[I.c], a[I.cat], a[I.t]);
      const pt: ForecastPoint = { date: a[I.d], days: +a[I.days], lo80: +a[I.lo80], hi80: +a[I.hi80], lo95: +a[I.lo95], hi95: +a[I.hi95] };
      (store.series.get(k) ?? store.series.set(k, []).get(k)!).push(pt);
    }
    if (metaJson.series) for (const [k, v] of Object.entries(metaJson.series)) store.meta.set(k.replace(/\//g, "|"), v);
    return store;
  })().catch(() => ({ method: {}, series: new Map(), meta: new Map() }));
  return cache;
}

export const forecastFor = (store: ForecastStore | null, country: string, category: string, table: string) =>
  store?.series.get(key(country, category, table)) ?? null;
export const forecastMetaFor = (store: ForecastStore | null, country: string, category: string, table: string) =>
  store?.meta.get(key(country, category, table)) ?? null;
