// BA5 — strict CSP without 'unsafe-inline' in script-src, for a static export.
//
// Why here and not netlify.toml: Next's App Router inlines its Flight payload
// as many per-page <script> chunks whose bytes change with every build, so the
// only robust way to hash them is AFTER `next build`, from the exact HTML that
// ships. This script runs as npm `postbuild`, walks out/**/*.html, sha256-hashes
// every inline script and writes per-page CSP rules into out/_headers.
//
// Decisions (documented for the next agent):
// - Per-PAGE rules (each page lists only its own hashes) instead of one giant
//   union rule: a union of ~130 hashes is a ~7 kB header on every response and
//   flirts with Netlify's header size limits; per-page CSPs stay ~1–2 kB.
// - No `/*` CSP fallback: Netlify merges netlify.toml + _headers and multiple
//   CSP values intersect (breaking the pages), so only exact page paths get a
//   policy. Non-document assets (images/CSS/JS) don't consume a document CSP.
//   Known gap: the soft-404 served for unknown paths carries no CSP (its
//   direct path /404.html does).
// - <script type="application/ld+json"> is a data block, never executed —
//   CSP3 does not apply script-src to it, so it is not hashed.
// - style-src keeps 'unsafe-inline' (Tailwind/React inline styles).
// - The base policy below is the single source of truth (moved verbatim from
//   netlify.toml, minus script-src's 'unsafe-inline').
import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { join, relative, sep } from "node:path";
import { glob } from "node:fs/promises";

const OUT = join(process.cwd(), "out");

const POLICY = (hashes) =>
  [
    "default-src 'self'",
    `script-src 'self' 'wasm-unsafe-eval' https://plausible.io${hashes.map((h) => ` '${h}'`).join("")}`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self' https://raw.githubusercontent.com https://plausible.io",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
  ].join("; ");

// Inline executable scripts only: no src attribute, and not a data block
// (application/ld+json). The hash covers the exact bytes between the tags.
function inlineScriptHashes(html) {
  const hashes = new Set();
  for (const m of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)) {
    const [, attrs, body] = m;
    if (/\bsrc\s*=/.test(attrs)) continue;
    if (/application\/(ld\+)?json/.test(attrs)) continue;
    hashes.add(`sha256-${createHash("sha256").update(body, "utf8").digest("base64")}`);
  }
  return [...hashes];
}

const rules = [];
const files = [];
for await (const f of glob("**/*.html", { cwd: OUT })) files.push(f);
files.sort();

for (const rel of files) {
  const html = await readFile(join(OUT, rel), "utf8");
  const csp = POLICY(inlineScriptHashes(html));
  const posix = rel.split(sep).join("/");
  // Netlify serves out/x/index.html at /x/ (and at /x/index.html); cover both.
  const urls = posix.endsWith("index.html")
    ? [`/${posix.slice(0, -"index.html".length)}`.replace(/\/+$/, "/") , `/${posix}`]
    : [`/${posix}`];
  for (const url of [...new Set(urls)]) {
    rules.push(`${url}\n  Content-Security-Policy: ${csp}`);
  }
}

if (files.length === 0) {
  console.error("build-csp: no HTML found in out/ — did next build run?");
  process.exit(1);
}

const banner =
  "# AUTO-GENERATED by scripts/build-csp.mjs (npm postbuild) — do not edit.\n" +
  "# Per-page CSP with sha256 hashes for every inline script (no 'unsafe-inline'\n" +
  "# in script-src). Other security headers live in netlify.toml.\n\n";
await writeFile(join(OUT, "_headers"), banner + rules.join("\n\n") + "\n");
console.log(`build-csp: _headers → CSP for ${files.length} pages (${rules.length} rules)`);
