// Derives the small set of site-wide headline stats from the data artifacts
// fetched at build time (public/data/eda_facts.json). Output is a tiny generated
// module the hero (and any other surface) imports — NO number is ever typed by
// hand in a component (regla #0). Runs in prebuild/predev after fetch-data.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const facts = JSON.parse(readFileSync(resolve(root, "public/data/eda_facts.json"), "utf8"));

const p = facts.panel;
for (const k of ["n_obs", "n_months", "n_series_structural", "pct_frozen", "date_first", "date_last"]) {
  if (p?.[k] == null) throw new Error(`eda_facts.json: panel.${k} missing — refusing to emit stale stats`);
}

// forecast horizon — derived from the forecasts artifact so build-time strings
// (SEO descriptions, section subtitles) never hand-type "12 months" (regla #0)
const fmeta = JSON.parse(readFileSync(resolve(root, "public/data/forecasts_meta.json"), "utf8"));
const horizonMonths = fmeta?.horizon_months;
if (!Number.isFinite(horizonMonths)) throw new Error("forecasts_meta.json: horizon_months missing — refusing to emit stale horizon");

const out = `// AUTO-GENERATED by scripts/build-stats.mjs from public/data/eda_facts.json.
// Do NOT edit by hand and do NOT hardcode these numbers in components (regla #0).
export const SITE_STATS = {
  nObs: ${p.n_obs},
  nMonths: ${p.n_months},
  nSeriesStructural: ${p.n_series_structural},
  pctFrozen: ${Math.round(p.pct_frozen)},
  dateFirst: ${JSON.stringify(p.date_first)},
  dateLast: ${JSON.stringify(p.date_last)},
  horizonMonths: ${horizonMonths},
} as const;
`;

writeFileSync(resolve(root, "lib/content/site-stats.generated.ts"), out);
console.log(`build-stats: nObs=${p.n_obs} nMonths=${p.n_months} range=${p.date_first}→${p.date_last} horizon=${horizonMonths}`);
