// Derives the small set of site-wide headline stats from the data artifacts
// fetched at build time (public/data/eda_facts.json). Output is a tiny generated
// module the hero (and any other surface) imports — NO number is ever typed by
// hand in a component (regla #0). Runs in prebuild/predev after fetch-data.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const facts = JSON.parse(readFileSync(resolve(root, "public/data/eda_facts.json"), "utf8"));

const p = facts.panel;
for (const k of ["n_obs", "n_months", "n_series_structural", "pct_frozen", "date_first", "date_last"]) {
  if (p?.[k] == null) throw new Error(`eda_facts.json: panel.${k} missing — refusing to emit stale stats`);
}

// forecast horizon — derived from the forecasts artifact so build-time strings
// (SEO descriptions, section subtitles) never hand-type "12 months" (regla #0)
const fmeta = JSON.parse(readFileSync(resolve(root, "public/data/forecasts_meta.json"), "utf8"));
const horizonMonths = fmeta?.horizon_months;
if (!Number.isFinite(horizonMonths) || horizonMonths <= 0) throw new Error("forecasts_meta.json: horizon_months missing or non-positive — refusing to emit stale horizon");

// n_models — size of the governed model catalog (comparison framework). The
// authoritative source lives in the DATA repo (reports/governance/key_facts.json
// → n_models, mirrored from docs/model_catalog.json), but NONE of the artifacts
// fetch-data currently downloads carries it (checked: eda_facts, fe_facts,
// forecasts_meta, forecast_scorecard_meta). Typed fallback so the number still
// has a SINGLE source inside this repo instead of being hand-typed in components.
// TODO(QW7): add reports/governance/key_facts.json to the data repo's release
// manifest + BASE_MAP in lib/release.mjs, then derive this from the fetched fact.
const nModels = 24;

// H3: provenance del corte servido — el loader B2 escribe release-state.json SIEMPRE
// (fresh/stale/legacy/incompatible); el footer lo muestra y el JSON queda
// machine-readable en /data/release-state.json. Tolerante: sin state → n/d.
let releaseId = "n/d";
let releaseStatus = "n/d";
try {
  const state = JSON.parse(readFileSync(resolve(root, "public/data/release-state.json"), "utf8"));
  releaseId = state.release_id ?? "n/d";
  releaseStatus = state.status ?? "n/d";
} catch {
  console.warn("build-stats: sin release-state.json — provenance n/d");
}

const body = `export const SITE_STATS = {
  nObs: ${p.n_obs},
  nMonths: ${p.n_months},
  nSeriesStructural: ${p.n_series_structural},
  pctFrozen: ${Math.round(p.pct_frozen)},
  dateFirst: ${JSON.stringify(p.date_first)},
  dateLast: ${JSON.stringify(p.date_last)},
  horizonMonths: ${horizonMonths},
  nModels: ${nModels},
  releaseId: ${JSON.stringify(releaseId)},
  releaseStatus: ${JSON.stringify(releaseStatus)},
}`;

const header = `// AUTO-GENERATED by scripts/build-stats.mjs from public/data/eda_facts.json.
// Do NOT edit by hand and do NOT hardcode these numbers in components (regla #0).`;

writeFileSync(resolve(root, "lib/content/site-stats.generated.ts"), `${header}\n${body} as const;\n`);
// Plain-ESM mirror for consumers that run under plain Node (no TS loader): the
// Netlify function (netlify/functions/chat.mjs) interpolates the forecast
// horizon into its system prompt (regla #0 — never hand-type "12 months").
// Emitted from the SAME run as the .ts, so the two can never drift.
writeFileSync(resolve(root, "lib/content/site-stats.generated.mjs"), `${header}\n${body};\n`);
console.log(`build-stats: nObs=${p.n_obs} nMonths=${p.n_months} range=${p.date_first}→${p.date_last} horizon=${horizonMonths} nModels=${nModels}`);
