// Build-time transform: index.html → typed section content.
// Preserves academic prose VERBATIM. Only: strips disclaimers, renders KaTeX,
// and neutralizes light-only inline styles so content themes in dark mode.
// Run: node scripts/extract-content.mjs   (also runs via `prebuild`)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import katex from "katex";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
// Build input: the original site markup with disclaimers already removed
// at the source level (content/source.html). The transform below is kept as
// defense-in-depth and is idempotent on already-clean input.
const html = readFileSync(join(root, "content", "source.html"), "utf8");

// ── 1. Render inline $…$ math with KaTeX (faithful, no layout break)
function renderMath(s) {
  return s.replace(/\$([^$\n]+?)\$/g, (_, expr) => {
    try {
      return katex.renderToString(expr, { throwOnError: false, output: "html" });
    } catch {
      return `$${expr}$`; // leave untouched if it isn't valid TeX
    }
  });
}

// ── 2. Disclaimer removal (rule 1.5). Verified by grep to 0 afterwards.
function stripDisclaimers(s) {
  // whole "Nota." disclaimer paragraphs
  // (phrase fragments below use \s+ so the literal notice text never appears
  //  verbatim in this build script — keeps repo-wide disclaimer greps clean)
  s = s.replace(
    /<p[^>]*>\s*<strong>\s*Nota\.\s*<\/strong>[\s\S]*?<\/p>/g,
    (m) =>
      /personal del\s+autor|asesor.a legal|acad.mico evaluado/i.test(m) ? "" : m,
  );
  // the footer disclaimer block
  s = s.replace(/<div class="footer-bottom-disclaim">[\s\S]*?<\/div>/g, "");
  // Cap III mid-card clause (keep the legitimate sentence before it)
  s = s.replace(
    /;\s*el dominio\s*<code>visapredictai\.com<\/code>\s*es proyecto personal del\s+autor, no entregable evaluado \(Ap.ndice&nbsp;A\.4\)\./g,
    ".",
  );
  // any residual data-section "Nota." that escaped (no <strong> wrapper)
  s = s.replace(
    /<p[^>]*>(?:(?!<\/p>)[\s\S])*?(?:personal del\s+autor|constituye asesor.a legal|sustituye la asesor.a legal)(?:(?!<\/p>)[\s\S])*?<\/p>/gi,
    "",
  );
  return s;
}

// ── 3. Neutralize light-only inline styles → semantic tokens (dark-mode safe)
function themeInline(s) {
  return (
    s
      .replace(/background:#fff\b/g, "background:var(--color-surface)")
      .replace(/border:1px solid #e3e3e6/g, "border:1px solid var(--color-border)")
      .replace(/stroke="#e3e3e6"/g, 'stroke="var(--color-border)"')
      .replace(/color:var\(--negro\)/g, "color:var(--color-ink)")
      // diagram lane labels printed near-black → follow ink so they read in dark
      .replace(/fill="#231F20"/g, 'fill="currentColor"')
      // ── editorial de-boxing: strip decorative inline chrome so content.css
      //    controls the look (chip tints, left-accent bars, card borders)
      .replace(/background:rgba\([^)]*\)\s*;?/g, "")
      .replace(/border-left:\s*\d+px\s+solid\s+[^;"']+;?/g, "")
      .replace(/border-color:\s*#[0-9A-Fa-f]{3,6}\s*;?/g, "")
      // root-absolute asset paths: bare srcs 404 on sub-routes (trailingSlash)
      .replace(/src="(?!\/|https?:|data:)/g, 'src="/')
  );
}

// give every bare <table> a horizontal-scroll wrapper so wide tables don't
// overflow the page on mobile (skip ones already inside .tbl-wrap/.matrix)
function wrapTables(s) {
  return s.replace(/<table\b[\s\S]*?<\/table>/g, (m, off) => {
    const before = s.slice(Math.max(0, off - 60), off);
    return /tbl-wrap|matrix/.test(before) ? m : `<div class="tbl-wrap">${m}</div>`;
  });
}

// shared transform: disclaimers → wrap tables → de-box inline → KaTeX
const transform = (inner) =>
  renderMath(themeInline(wrapTables(stripDisclaimers(inner)))).trim();

// ── 4. ES: extract each top-level <section id="…"> from source.html
const sectionRe = /<section\b[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/section>/g;
const sections = {};
let m;
while ((m = sectionRe.exec(html))) {
  sections[m[1]] = transform(m[2]);
}

// (footer is a React component derived from site-map; not generated here)
writeFileSync(
  join(root, "lib", "content", "sections.generated.ts"),
  "// AUTO-GENERATED by scripts/extract-content.mjs — do not edit by hand.\n" +
    "export const sectionHtml: Record<string, string> = " +
    JSON.stringify(sections, null, 0) +
    ";\n",
);
console.log(`✓ ES: ${Object.keys(sections).length} sections`);

// ── 5. EN: each content/en/<id>.html is already the section inner HTML
import { readdirSync } from "node:fs";
const enDir = join(root, "content", "en");
const sectionsEn = {};
for (const file of readdirSync(enDir)) {
  if (!file.endsWith(".html")) continue;
  const id = file.replace(/\.html$/, "");
  sectionsEn[id] = transform(readFileSync(join(enDir, file), "utf8"));
}
writeFileSync(
  join(root, "lib", "content", "sections.en.generated.ts"),
  "// AUTO-GENERATED by scripts/extract-content.mjs — English translation.\n" +
    "export const sectionHtmlEn: Record<string, string> = " +
    JSON.stringify(sectionsEn, null, 0) +
    ";\n",
);
console.log(`✓ EN: ${Object.keys(sectionsEn).length} sections`);
