// Build-time transform: index.html → typed section content.
// Preserves academic prose VERBATIM. Only: strips disclaimers, renders KaTeX,
// and neutralizes light-only inline styles so content themes in dark mode.
// Run: node scripts/extract-content.mjs   (also runs via `prebuild`)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import katex from "katex";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
// Build input: the original site markup with disclaimers already removed
// at the source level (content/source.html). The transform below is kept as
// defense-in-depth and is idempotent on already-clean input.
const html = readFileSync(join(root, "content", "source.html"), "utf8");

// ── 1. Render inline $…$ math with KaTeX (faithful, no layout break)
function renderMath(s) {
  return s.replace(/\$([^$\n]+?)\$/g, (_, expr) => {
    try {
      return katex.renderToString(expr, { throwOnError: false, output: "html" });
    } catch {
      return `$${expr}$`; // leave untouched if it isn't valid TeX
    }
  });
}

// ── 2. Disclaimer removal (rule 1.5). Verified by grep to 0 afterwards.
function stripDisclaimers(s) {
  // whole "Nota." disclaimer paragraphs
  // (phrase fragments below use \s+ so the literal notice text never appears
  //  verbatim in this build script — keeps repo-wide disclaimer greps clean)
  s = s.replace(
    /<p[^>]*>\s*<strong>\s*Nota\.\s*<\/strong>[\s\S]*?<\/p>/g,
    (m) =>
      /personal del\s+autor|asesor.a legal|acad.mico evaluado/i.test(m) ? "" : m,
  );
  // the footer disclaimer block
  s = s.replace(/<div class="footer-bottom-disclaim">[\s\S]*?<\/div>/g, "");
  // Cap III mid-card clause (keep the legitimate sentence before it)
  s = s.replace(
    /;\s*el dominio\s*<code>visapredictai\.com<\/code>\s*es proyecto personal del\s+autor, no entregable evaluado \(Ap.ndice&nbsp;A\.4\)\./g,
    ".",
  );
  // any residual data-section "Nota." that escaped (no <strong> wrapper)
  s = s.replace(
    /<p[^>]*>(?:(?!<\/p>)[\s\S])*?(?:personal del\s+autor|constituye asesor.a legal|sustituye la asesor.a legal)(?:(?!<\/p>)[\s\S])*?<\/p>/gi,
    "",
  );
  return s;
}

// ── 3. Neutralize light-only inline styles → semantic tokens (dark-mode safe)
function themeInline(s) {
  return (
    s
      .replace(/background:#fff\b/g, "background:var(--color-surface)")
      .replace(/border:1px solid #e3e3e6/g, "border:1px solid var(--color-border)")
      .replace(/stroke="#e3e3e6"/g, 'stroke="var(--color-border)"')
      .replace(/color:var\(--negro\)/g, "color:var(--color-ink)")
      // diagram lane labels printed near-black → follow ink so they read in dark
      .replace(/fill="#231F20"/g, 'fill="currentColor"')
      // ── editorial de-boxing: strip decorative inline chrome so content.css
      //    controls the look (chip tints, left-accent bars, card borders)
      .replace(/background:rgba\([^)]*\)\s*;?/g, "")
      .replace(/border-left:\s*\d+px\s+solid\s+[^;"']+;?/g, "")
      .replace(/border-color:\s*#[0-9A-Fa-f]{3,6}\s*;?/g, "")
  );
}

// ── 4. Extract each top-level <section id="…"> (sections do not nest)
const sectionRe = /<section\b[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/section>/g;
const sections = {};
let m;
while ((m = sectionRe.exec(html))) {
  const id = m[1];
  let inner = m[2];
  inner = stripDisclaimers(inner);
  inner = themeInline(inner);
  inner = renderMath(inner);
  sections[id] = inner.trim();
}

// footer (strip disclaimer, keep nav columns + copyright)
const footerMatch = html.match(/<footer class="footer">([\s\S]*?)<\/footer>/);
let footer = footerMatch ? footerMatch[1] : "";
footer = themeInline(renderMath(stripDisclaimers(footer))).trim();

// ── 5. Emit typed module
const out =
  "// AUTO-GENERATED by scripts/extract-content.mjs — do not edit by hand.\n" +
  "// Academic prose preserved verbatim from index.html. Disclaimers stripped, KaTeX rendered.\n" +
  "export const sectionHtml: Record<string, string> = " +
  JSON.stringify(sections, null, 0) +
  ";\n\nexport const footerHtml: string = " +
  JSON.stringify(footer) +
  ";\n";

writeFileSync(join(root, "lib", "content", "sections.generated.ts"), out);

const ids = Object.keys(sections);
console.log(`✓ extracted ${ids.length} sections: ${ids.join(", ")}`);
console.log(`✓ footer ${footer.length} chars`);
